parameters:
      class: aiagents.multi.BasicComplexAgent.BasicComplexAgent
      parameters: {}
      subAgentList:
          - class: aiagents.single.mcts.MctsAgent.MctsAgent
            id: "robot1"
            parameters:
              timeLimit: 10
              treeParameters: 
                explorationConstant: 10
                samplingLimit: 20
              treeAgent:
                class: aiagents.single.RandomAgent.RandomAgent
                id: "robot1"
                parameters: {}
              rolloutAgent:
                class: aiagents.single.RandomAgent.RandomAgent
                id: "robot1"
                parameters: {}
              otherAgents:
                    class: aiagents.multi.BasicComplexAgent.BasicComplexAgent
                    parameters: {}
                    subAgentList:
                      - class: aiagents.single.FactoryFloorAgent.FactoryFloorAgent
                        id: "robot2"
                        parameters: {}
          - class: aiagents.single.mcts.MctsAgent.MctsAgent
            id: "robot2"
            parameters:
              timeLimit: 10
              treeParameters: 
                explorationConstant: 10
                samplingLimit: 20
              treeAgent:
                class: aiagents.single.RandomAgent.RandomAgent
                id: "robot2"
                parameters: {}
              rolloutAgent:
                class: aiagents.single.RandomAgent.RandomAgent
                id: "robot2"
                parameters: {}
              otherAgents:
                  class: aiagents.multi.BasicComplexAgent.BasicComplexAgent
                  parameters: {}
                  subAgentList:
                    - class: aiagents.single.FactoryFloorAgent.FactoryFloorAgent
                      id: "robot1"
                      parameters: {}

